import type { Locale, SectionKey, ProjectTrack } from "./types";

export const copy = {
  pt: {
    skip: "Pular para o conteúdo", menu: "Abrir menu", closeMenu: "Fechar menu",
    language: "Ver este portfólio em inglês", otherLanguage: "EN",
    nav: ["Início", "Projetos", "Sobre", "Arquivo", "Formação", "Contato", "Terminal"],
    app: ["bem-vindo.exe", "projetos/", "digital_me.exe", "arquivo/", "formacao.sys", "connect.exe", "terminal.exe"],
    startupTitle: "Sua próxima ideia começa aqui.",
    startupDesc: "Explore meu trabalho dentro de uma workstation digital. Você escolhe: entrar direto ou assistir à inicialização.",
    enter: "Entrar no workspace", boot: "Ver inicialização", skipBoot: "Pular inicialização",
    bootLines: ["Montando ZARA_DISK", "Carregando projetos selecionados", "Iniciando o ambiente"],
    activeApp: "APP ATIVO", available: "Aberto a oportunidades", work: "FOCUS MODE",
    profileKicker: "Rodrigo Pinheiro / Zara Takion", role: "Desenvolvedor Web Júnior · Back-end Python",
    heroTitle: "Construo sistemas web que fazem sentido",
    heroDesc: "Transformo requisitos em aplicações web claras, APIs documentadas e experiências úteis. Meu trabalho combina engenharia de software, preocupação com usabilidade e decisões técnicas explicáveis.",
    projectsCTA: "Explorar projetos", contactCTA: "Entrar em contato",
    sectionIndex: "ZARA_DISK / HOME", heroYear: "PORTFÓLIO · 2026",
    projectTitle: "Trabalho selecionado", projectDesc: "Projetos reais apresentados como estudos de caso — problema, implementação, arquitetura e limites, sem resultados inventados.",
    archiveTitle: "Outras explorações", archiveDesc: "Experimentos, análises de dados e ferramentas que ampliam meu repertório.",
    filter: "Filtrar projetos", filters: ["Todos", "Web", "APIs", "Dados"],
    noProjects: "Nenhum projeto encontrado nesta categoria.", loading: "Carregando acervo...", error: "Não foi possível carregar os projetos. Confira sua conexão.",
    caseStudy: "Estudo de caso", problem: "Problema", approach: "Implementação", architecture: "Arquitetura", verification: "Verificação", boundary: "Limites",
    repository: "Ver repositório", demo: "Abrir demonstração", technology: "Tecnologias",
    selectProject: "Selecione um projeto", folders: "pastas",
    profileTitle: "Código claro, decisões explicáveis.",
    profile1: "Sou Rodrigo Araújo Maciel Pinheiro, conhecido profissionalmente como Zara Takion. Sou tecnólogo em Sistemas para Internet e desenvolvedor web júnior com foco em back-end.",
    profile2: "Construo APIs, interfaces e aplicações web com atenção às pessoas que vão utilizá-las. Prefiro mostrar resultados verificáveis, decisões arquiteturais e os limites reais de cada projeto.",
    stackTitle: "COMPETÊNCIAS / SYSTEM_CAPABILITIES",
    stackLabels: ["Back-end & APIs", "Front-end", "Dados", "Ferramentas"],
    techDisclaimer: "Tecnologias listadas conforme aparecem em projetos e estudos demonstráveis.",
    educationTitle: "Base e repertório", educationDesc: "Formação acadêmica e idiomas usados em contexto técnico.",
    degree: "Tecnólogo em Sistemas para Internet", institution: "Centro Universitário UNIESP · Cabedelo, Paraíba",
    done: "CONCLUÍDO · 2026", languageTitle: "Comunicação em contexto técnico", native: "Nativo", englishLevel: "Intermediário · leitura B2",
    contactTitle: "Vamos construir alguma coisa?", contactDesc: "Estou aberto a oportunidades profissionais e conversas sobre desenvolvimento web, APIs, interfaces e back-end Python.",
    github: "GitHub", linkedin: "LinkedIn", email: "E-mail", professional: "Perfil profissional",
    copyright: "Desenvolvedor Web Júnior · Paraíba, Brasil", privacy: "Privacidade",
    minimize: "Minimizar janela", close: "Fechar janela", fullscreen: "Expandir janela", restore: "Restaurar tamanho",
    terminalWelcome: "AQUA_TERMINAL // comandos seguros de navegação", terminalHint: "Digite help para ver os comandos disponíveis.",
    terminalHelp: "Comandos: help · projects · about · skills · archive · education · contact · home · clear",
    terminalUnknown: "Comando não reconhecido. Digite help.", terminalLabel: "Comando do terminal",
    terminalRun: "Executar", terminalClear: "Limpar", terminalTitle: "Terminal de navegação",
    shortcuts: "Atalhos: Alt+1–7 para abrir aplicativos · Esc para voltar ao início.",
    openApp: "Abrir aplicativo", status: "Estado da workstation", archiveLabel: "Arquivo de projetos",
    liveMode: "MODO AQUA", start: "INICIAR",
  },
  en: {
    skip: "Skip to content", menu: "Open menu", closeMenu: "Close menu",
    language: "View this portfolio in Portuguese", otherLanguage: "PT",
    nav: ["Home", "Projects", "About", "Archive", "Education", "Contact", "Terminal"],
    app: ["welcome.exe", "projects/", "digital_me.exe", "archive/", "education.sys", "connect.exe", "terminal.exe"],
    startupTitle: "Your next idea begins here.",
    startupDesc: "Explore my work in a digital workstation. You choose: enter directly or watch a short boot sequence.",
    enter: "Enter workspace", boot: "Watch startup", skipBoot: "Skip introduction",
    bootLines: ["Mounting ZARA_DISK", "Loading selected projects", "Starting the workspace"],
    activeApp: "ACTIVE APP", available: "Open to opportunities", work: "FOCUS MODE",
    profileKicker: "Rodrigo Pinheiro / Zara Takion", role: "Junior Web Developer · Python Back End",
    heroTitle: "I build web systems that make sense",
    heroDesc: "I turn requirements into clear web applications, documented APIs and useful experiences. My work combines software engineering, usability and explainable technical decisions.",
    projectsCTA: "Explore projects", contactCTA: "Get in touch",
    sectionIndex: "ZARA_DISK / HOME", heroYear: "PORTFOLIO · 2026",
    projectTitle: "Selected work", projectDesc: "Real projects presented as case studies — problem, implementation, architecture and limitations, without invented outcomes.",
    archiveTitle: "Other explorations", archiveDesc: "Experiments, data analysis and tools that expand my craft.",
    filter: "Filter projects", filters: ["All", "Web", "APIs", "Data"],
    noProjects: "No projects in this category.", loading: "Loading projects...", error: "Could not load projects. Please check your connection.",
    caseStudy: "Case study", problem: "Problem", approach: "Implementation", architecture: "Architecture", verification: "Verification", boundary: "Boundaries",
    repository: "View repository", demo: "Open live demo", technology: "Technologies",
    selectProject: "Select a project", folders: "folders",
    profileTitle: "Clear code, explainable decisions.",
    profile1: "I'm Rodrigo Araújo Maciel Pinheiro, professionally known as Zara Takion. I hold a degree in Internet Systems Technology and work as a junior web developer with a back-end focus.",
    profile2: "I build APIs, interfaces and web applications with attention to the people using them. I prefer demonstrable results, architectural decisions and honest limitations over exaggerated claims.",
    stackTitle: "SKILLS / SYSTEM_CAPABILITIES",
    stackLabels: ["Back end & APIs", "Front end", "Data", "Tools"],
    techDisclaimer: "Technologies listed are represented in demonstrable projects and studies.",
    educationTitle: "Background and experience", educationDesc: "Academic education and languages in a technical setting.",
    degree: "Technology degree in Internet Systems", institution: "UNIESP University Center · Cabedelo, Paraíba, Brazil",
    done: "COMPLETED · 2026", languageTitle: "Technical communication", native: "Native", englishLevel: "Intermediate · B2 reading proficiency",
    contactTitle: "Shall we build something?", contactDesc: "I'm open to professional opportunities and conversations about web development, APIs, user interfaces and Python back ends.",
    github: "GitHub", linkedin: "LinkedIn", email: "E-mail", professional: "Professional profile",
    copyright: "Junior Web Developer · Paraíba, Brazil", privacy: "Privacy",
    minimize: "Minimize window", close: "Close window", fullscreen: "Maximize window", restore: "Restore window",
    terminalWelcome: "AQUA_TERMINAL // safe navigation commands", terminalHint: "Type help to list supported commands.",
    terminalHelp: "Commands: help · projects · about · skills · archive · education · contact · home · clear",
    terminalUnknown: "Unknown command. Type help.", terminalLabel: "Terminal command",
    terminalRun: "Run", terminalClear: "Clear", terminalTitle: "Navigation terminal",
    shortcuts: "Shortcuts: Alt+1–7 to open apps · Esc to return home.",
    openApp: "Open app", status: "Workstation status", archiveLabel: "Project archive",
    liveMode: "AQUA MODE", start: "START",
  },
} as const;

export const appKeys: SectionKey[] = ["home", "projects", "about", "archive", "education", "contact", "terminal"];
export const tracks: ProjectTrack[] = ["all", "web", "api", "data"];
export function translate(locale: Locale) { return copy[locale]; }
